### ISSUE TITLE
原始数据里面owner_domain为空的情况下，$ipdb_isp_domain的前面会多出一个tab符

### ISSUE THREAD

**Issue by michael9987** [vislee/ngx_http_ipdb_module#1]
测试用例：
58.250.137.36
"	联通"
59.65.210.0
"教育网"

**Comment by michael9987** [comment]
@vislee 辛苦帮看一下

**Comment by vislee** [comment]
@michael9987  是个bug，已经修复[https://github.com/vislee/ngx_http_ipdb_module/commit/c38e2b7fa664a3cb69f6b7defd2b3929d231f5e5](https://github.com/vislee/ngx_http_ipdb_module/commit/c38e2b7fa664a3cb69f6b7defd2b3929d231f5e5) 。 再试试～

**Comment by michael9987** [comment]
@vislee 给力
