### ISSUE TITLE
如何同时加载 ipv4 和 ipv6 ipdb

### ISSUE THREAD

**Issue by selboo** [vislee/ngx_http_ipdb_module#10]
ipdb
----
**syntax:** *ipdb file;*

**default:** *-*

**context:** *http*

Specifies a database.

ipdb 参数只能加载一个文件, 要么是 `ipv4.ipdb` 或 `ipv6.ipdb`

现在大部分都多支持双栈, 如何同时加载 `ipv4` 和 `ipv6` 文件, 以便 v4 v6 地址都支持

**Comment by ipipdotnet** [comment]
IPv4与IPv6 可以共用一个ipdb格式的文件 请联系我。@selboo

**Comment by selboo** [comment]
> IPv4与IPv6 可以共用一个ipdb格式的文件 请联系我。@selboo

如何联系您? 我邮箱  xuguocan@gmail.com

**Comment by ipipdotnet** [comment]
> > IPv4与IPv6 可以共用一个ipdb格式的文件 请联系我。@selboo
> 
> 如何联系您? 我邮箱 [xuguocan@gmail.com](mailto:xuguocan@gmail.com)

我给你发邮件了
