### ISSUE TITLE
ipdb_proxy_recursive开启的情况下取到的是最后一个IP的数据

### ISSUE THREAD

**Issue by michael9987** [vislee/ngx_http_ipdb_module#2]
例如X-Forwarded-For字段如下
X-Forwarded-For: client, proxy1, proxy2
配置：ipdb_proxy_recursive on;
通过这个模块会得到proxy2的IP信息，而不是client的ip信息
@vislee

**Comment by vislee** [comment]
参考nginx geoip模块的 [geoip_proxy](http://nginx.org/en/docs/http/ngx_http_geoip_module.html#geoip_proxy)指令，你需要用指令`ipdb_proxy` 指定信任IP。
