### ISSUE TITLE
failed to compile it into nginx

### ISSUE THREAD

**Issue by vampire007** [vislee/ngx_http_ipdb_module#3]
Hi~ ngx_http_ipdb_module/ngx_http_ipdb_module.c:146:7: error: 'ngx_http_null_variable' undeclared here (not in a function)

ngx_http_null_variable is not defined which lead to error in compiling it into nginx

**Comment by vampire007** [comment]
ngx_http_null_variable  =>ngx_null_command 就OK了。

**Comment by vislee** [comment]
> ngx_http_null_variable =>ngx_null_command 就OK了。

No, if you nginx Less than release-1.13.4, you can replace with `{ ngx_null_string, NULL, NULL, 0, 0, 0 }`。  Reference to [define](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_variables.h#L46).

**Comment by vislee** [comment]
fix 9d7021b. try again.

**Comment by vampire007** [comment]
great ~ when will you add other ip info variables? like ipdb_idc/ipdb_base_station?

**Comment by vislee** [comment]
> great ~ when will you add other ip info variables? like ipdb_idc/ipdb_base_station?

Has been added.
