### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by GuerraMorgan** [vislee/ngx_http_ipdb_module#7]
centos 7
kernel 5
gcc 8
nginx 1.17.6

/www/server/nginx/src/ngx_http_ipdb_module/ipdb/ipdb.c: In function ‘ipdb_reader_new’:
/www/server/nginx/src/ngx_http_ipdb_module/ipdb/ipdb.c:106:5: error: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Werror=unused-result]
     fread(&meta_length, sizeof(meta_length), 1, fd);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/www/server/nginx/src/ngx_http_ipdb_module/ipdb/ipdb.c:111:5: error: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Werror=unused-result]
     fread(meta_json, sizeof(char), meta_length, fd);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/www/server/nginx/src/ngx_http_ipdb_module/ipdb/ipdb.c:124:5: error: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Werror=unused-result]
     fread(rd->data, sizeof(unsigned char), (size_t) data_len, fd);

**Comment by GuerraMorgan** [comment]
@vislee

**Comment by vislee** [comment]
ipdb库的警告，忽略，不影响结果。
