### ISSUE TITLE
变量为空

### ISSUE THREAD

**Issue by helloxz** [vislee/ngx_http_ipdb_module#9]
配置如下：
HTTP段：
```nginx
ipdb /root/ipipfree.ipdb;
ipdb_language EN;
ipdb_proxy 127.0.0.1;
    ipdb_proxy_recursive on;
```

Server段内容为：

```
add_header x-info $ipdb_country_name;
add_header x-test $ipdb_region_name;
```

发现response中不返回`x-info`（$ipdb_country_name），结果为空，重启过nginx，同时nginx中无错误日志，请问是怎么回事？

**Comment by helloxz** [comment]
找到一个相同的问题：https://www.gitmemory.com/issue/vislee/ngx_http_ipdb_module/5/654618145

**Comment by vislee** [comment]
和 #5 一样， ipip免费的库没有英文的数据。

**Comment by helloxz** [comment]
好的，感谢。
